CREATE OR REPLACE FUNCTION outcome ( grade int )
RETURNS TEXT
AS
$$
	DECLARE
		PASS_THRESHOLD CONSTANT int = 40;
		COMPENSATION_THRESHOLD CONSTANT int = 35;
	BEGIN
		IF ( grade >= PASS_THRESHOLD )
		THEN
			RETURN 'PASS';
		ELSIF ( grade >= COMPENSATION_THRESHOLD )
		THEN
			RETURN 'PASS BY COMPENSATION';
		ELSE
			RETURN 'FAIL';
		END IF;
		
	END;
$$
LANGUAGE plpgsql
;
